language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "export PYTHONPATH=." # It's needed to correctly run tests
# command to run tests
script: py.test .
